### PR TITLE
Nextjs zip download from url

### PR DESCRIPTION
**Pull request by ErikRZH**

### CODE REVIEW

**Comment by phongvis** [comment]
```
{
  "name": "example_structured_data",
  "url": "https://github.com/rampvisdevelopment/example_data_respository/archive/main.zip",
  "save_to": "example_folder"
}
```

Given that example, the data is actually downloaded under `example_folder/example_data_respository-main`. One may expect that the data is directly under `example_folder` just like in the case of a single file `models/sobol/raw.json`. Otherwise, one needs to manually guess the subfolder's name (probably {repo}-{branch}) to access the downloaded data.

Does it make sense? If yes, could you make the change?

**Comment by ErikRZH** [comment]
Hi @phongvis that's a good point, I will make that change.

**Comment by ErikRZH** [comment]
@phongvis It has been modified to behave the same way as the other url downloads now. Meaning that the contents of the github repo are placed directly in a directory given by url[save_to]. Was this what you intended?

**Comment by phongvis** [comment]
I got an error when testing 

```
    zipinfo.filename = zipinfo.filename.removeprefix(zipinfo.filename.split('/')[0])  #Removes the top level folder when extracting
AttributeError: 'str' object has no attribute 'removeprefix'
```

**Pull request merged**
