### PR TITLE
Feature timeseriessim

### PR DESCRIPTION
**Pull request by tunagonen**
First run api: including search and retrieval functions, preprocessing and cube generation

### CODE REVIEW

**Review by phongvis — COMMENTED** [review]
I don't know what to expect from this PR so can't comment on specific feature, looks like lots of changes.

Just a couple of comments:
1/ Please not committing the four data .csv files. The changes are caused by the downloader agents rather than your code. So, excluding them makes your PR leaner.
2/ I don't have any comments about the 4 python files with 'sim_search' - you can take your full ownership now. The only thing I wonder is the change you make for `main.py`. Why did you need to change it and @saifulkhan is it ok?

**Comment by tunagonen** [comment]
Hey Phong sorry for uploading a big chunk. The change in the main.py was due to the CORS errors I was getting when trying to test API and UI locally. I wrote it to slack and to continue, I made a temporary fix which allows requests from all origins.

**Comment by saifulkhan** [comment]
1. The main.py change opens/allows traffic from all sources to our server. This change has to be discarded. 
2. Data should be downloaded or processed by download or other agents/schedulers when services are started. Do not commit any data (CSV) files to the repository unless it is absolutely necessary. 
3. From my quick scan of Erik's PR, it looks like he is uploading the data somewhere and downloading it from there instead of committing it to this repository.

**Comment by phongvis** [comment]
OK, looks good now. I'll merge now.

**Pull request merged**
